a = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(a))
print('Só tem espaços? ', a.isspace())
print('É um número? ', a.isnumeric())
print('É alfabético? ', a.isalpha())
print('É alfanumérico? ', a.isalnum())
print('Está em maiúsculas? ', a.isupper())
print('Está em minúsculas? ', a.islower())
print(f'Está capitalizado? ', a.istitle())

# print(f'Só tem espaços? {a.isspace()}')
# print(f'É um número? {a.isnumeric()}')
# print(f'É alfabético? {a.isalpha()}')
# print(f'É alfanumérico? {a.isalnum()}')
# print(f'Está em maiúsculas? {a.isupper()}')
# print(f'Está em minúsculas? {a.islower()}')
# print(f'Está capitalizado? {a.istitle()}')
