#   TABUADA
print('='*33, 'TABUADA', '='*34)

n = int(input('Digite um numero:'))

print('='*30, 'TABUADA ADIÇÃO', '='*30)
print(f'{n} + {1} = {n+1}')
print(f'{n} + {2} = {n+2}')
print(f'{n} + {3} = {n+3}')
print(f'{n} + {4} = {n+4}')
print(f'{n} + {5} = {n+5}')
print(f'{n} + {6} = {n+6}')
print(f'{n} + {7} = {n+7}')
print(f'{n} + {8} = {n+8}')
print(f'{n} + {9} = {n+9}')
print(f'{n} + {10} = {n+10}')

print('='*30, 'TABUADA SUBTRAÇÃO', '='*30)
print(f'{n} - {n} = {n-n}')
print(f'{n} - {n+1} = {n-(n+1)}')
print(f'{n} - {n+2} = {n-(n+2)}')
print(f'{n} - {n+3} = {n-(n+3)}')
print(f'{n} - {n+4} = {n-(n+4)}')
print(f'{n} - {n+5} = {n-(n+5)}')
print(f'{n} - {n+6} = {n-(n+6)}')
print(f'{n} - {n+7} = {n-(n+7)}')
print(f'{n} - {n+8} = {n-(n+8)}')
print(f'{n} - {n+9} = {n-(n+9)}')
print(f'{n} - {n+10} = {n-(n+10)}')


print('='*30, 'TABUADA MULTIPLICAÇÃO', '='*30)
print(f'{n} x {1} = {n*1}')
print(f'{n} x {2} = {n*2}')
print(f'{n} x {3} = {n*3}')
print(f'{n} x {4} = {n*4}')
print(f'{n} x {5} = {n*5}')
print(f'{n} x {6} = {n*6}')
print(f'{n} x {7} = {n*7}')
print(f'{n} x {8} = {n*8}')
print(f'{n} x {9} = {n*9}')
print(f'{n} x {10} = {n*10}')

print('='*30, 'TABUADA DIVISÃO', '='*30)
print(f'{n} / {1} = {n/1:.1f}')
print(f'{n} / {2} = {n/2:.1f}')
print(f'{n} / {3} = {n/3:.1f}')
print(f'{n} / {4} = {n/4:.1f}')
print(f'{n} / {5} = {n/5:.1f}')
print(f'{n} / {6} = {n/6:.1f}')
print(f'{n} / {7} = {n/7:.1f}')
print(f'{n} / {8} = {n/8:.1f}')
print(f'{n} / {9} = {n/9:.1f}')
print(f'{n} / {10} = {n/10:.1f}')
